### ISSUE TITLE
Adding a RichTextEditor to a nested content item in the documenttype, used in DTGE returns an error. Umbraco 8.2

### ISSUE THREAD

**Issue by ThomSeys** [skttl/umbraco-doc-type-grid-editor#165]
Hi, 

We added DTGE to our detailpages and for some components in it, we created a doctype with a title (substring) and content (nested content). It doesn not throw an error in Umbraco itself, but on the webpage, it throws the error shown below. 

System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Web.PropertyEditors.RichTextPropertyEditor.RichTextPropertyValueEditor.FromEditor(ContentPropertyData editorValue, Object currentValue) in d:\a\1\s\src\Umbraco.Web\PropertyEditors\RichTextPropertyEditor.cs:line 117
   at Umbraco.Web.PropertyEditors.NestedContentPropertyEditor.NestedContentPropertyValueEditor.FromEditor(ContentPropertyData editorValue, Object currentValue) in d:\a\1\s\src\Umbraco.Web\PropertyEditors\NestedContentPropertyEditor.cs:line 251
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValue(String id, String contentTypeAlias, String dataJson)
   at Umbraco.Core.Cache.AppCacheExtensions.<>c__DisplayClass5_0`1.<GetCacheItem>b__0() in d:\a\1\s\src\Umbraco.Core\Cache\AppCacheExtensions.cs:line 62
   at Umbraco.Core.Cache.FastDictionaryAppCacheBase.<>c__DisplayClass21_0.<GetSafeLazy>b__0() in d:\a\1\s\src\Umbraco.Core\Cache\FastDictionaryAppCacheBase.cs:line 285
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Core.Cache.HttpRequestAppCache.Get(String key, Func`1 factory) in d:\a\1\s\src\Umbraco.Core\Cache\HttpRequestAppCache.cs:line 81
   at Umbraco.Core.Cache.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem) in d:\a\1\s\src\Umbraco.Core\Cache\AppCacheExtensions.cs:line 62
   at ASP._Page_App_Plugins_DocTypeGridEditor_Render_DocTypeGridEditor_cshtml.Execute() in C:\..\App_Plugins\DocTypeGridEditor\Render\DocTypeGridEditor.cshtml:line 26
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at Umbraco.Web.Mvc.ProfilingView.Render(ViewContext viewContext, TextWriter writer) in d:\a\1\s\src\Umbraco.Web\Mvc\ProfilingView.cs:line 25
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Page_Views_Partials_grid_editors_Base_cshtml.Execute() in C:\..\Views\Partials\grid\editors\Base.cshtml:line 20

**Comment by skttl** [comment]
8.2.0?

**Comment by ThomSeys** [comment]
Yes! :)

**Comment by skttl** [comment]
Sorry about that, there was a bug in Umbraco 8.2.0, which makes it incompatible with DTGE. You need at least 8.2.1 for it to work.
