### ISSUE TITLE
Image Cropper on doctype

### ISSUE THREAD

**Issue by D-Houghton** [skttl/umbraco-doc-type-grid-editor#177]
Using Umbraco 8.5.2

Attached image cropper datatype to doctype used by dtge, and then view throws the following system exception error:

System.Exception: Invalid content key.
   at Umbraco.Web.PropertyEditors.ImageCropperPropertyValueEditor.FromEditor(ContentPropertyData editorValue, Object currentValue) in D:\a\1\s\src\Umbraco.Web\PropertyEditors\ImageCropperPropertyValueEditor.cs:line 98
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValue(String id, String contentTypeAlias, String dataJson)
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.<>c__DisplayClass0_0.<ConvertValueToContent>b__0()
   at Umbraco.Core.Cache.AppCacheExtensions.<>c__DisplayClass5_0`1.<GetCacheItem>b__0() in D:\a\1\s\src\Umbraco.Core\Cache\AppCacheExtensions.cs:line 62
   at Umbraco.Core.Cache.FastDictionaryAppCacheBase.<>c__DisplayClass21_0.<GetSafeLazy>b__0() in D:\a\1\s\src\Umbraco.Core\Cache\FastDictionaryAppCacheBase.cs:line 285
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Core.Cache.HttpRequestAppCache.Get(String key, Func`1 factory) in D:\a\1\s\src\Umbraco.Core\Cache\HttpRequestAppCache.cs:line 81
   at Umbraco.Core.Cache.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem) in D:\a\1\s\src\Umbraco.Core\Cache\AppCacheExtensions.cs:line 62
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValueToContent(String id, String contentTypeAlias, String dataJson)
   at ASP._Page_app_plugins_doctypegrideditor_render_DocTypeGridEditor_cshtml.Execute() in {PATH}\app_plugins\doctypegrideditor\render\DocTypeGridEditor.cshtml:line 26
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Web.Mvc.ProfilingView.Render(ViewContext viewContext, TextWriter writer) in D:\a\1\s\src\Umbraco.Web\Mvc\ProfilingView.cs:line 25
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at ASP._Page_Views_Partials_grid_editors_Base_cshtml.Execute() in {PATH}\Views\Partials\grid\editors\Base.cshtml:line 20

**Comment by skttl** [comment]
Hi @D-Houghton 

Image Cropper is not supported in DTGE, because it needs a real node in order to know where to save the file you upload.

https://github.com/skttl/umbraco-doc-type-grid-editor#known-issues
