### ISSUE TITLE
Install Errror

### ISSUE THREAD

**Issue by thenexus00** [skttl/umbraco-doc-type-grid-editor#197]
I am getting a failed restart error when installing the latest version of the package on the latest Umbraco 8.

I get the following error:

`-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Reflection.ReflectionTypeLoadException: Could not load all types from "Our.Umbraco.DocTypeGridEditor, Version=1.2.7422.26062, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.PropertyEditors.IDataValueReferenceFactory: Could not load type 'Umbraco.Core.PropertyEditors.IDataValueReferenceFactory' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.

  at Umbraco.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a) in d:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 572
  at Umbraco.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter) in d:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 504
  at Umbraco.Core.Composing.TypeLoader.<>c__DisplayClass50_0`1.<GetTypes>b__1() in d:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 542
  at Umbraco.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in d:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 752
  at Umbraco.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in d:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 656
  at Umbraco.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies) in d:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 540
  at Umbraco.Core.Runtime.CoreRuntime.ResolveComposerTypes(TypeLoader typeLoader) in d:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 275
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in d:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 149`

**Comment by skttl** [comment]
How are you installing?

**Comment by enkelmedia** [comment]
What version of Umbraco are you trying to install on?

**Comment by skttl** [comment]
@thenexus00 I need some more info on this to investigate...

**Comment by tunaweb** [comment]
Hi Just to say have had a similar error installing from the back office on v8.2.3

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Reflection.ReflectionTypeLoadException: Could not load all types from "Our.Umbraco.DocTypeGridEditor, Version=1.2.7439.32789, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.PropertyEditors.IDataValueReferenceFactory: Could not load type 'Umbraco.Core.PropertyEditors.IDataValueReferenceFactory' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.

   at Umbraco.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
   at Umbraco.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter)
   at Umbraco.Core.Composing.TypeFinder.FindClassesOfType[T](IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Core.Composing.TypeLoader.<>c__DisplayClass50_0`1.<GetTypes>b__1()
   at Umbraco.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Core.Runtime.CoreRuntime.GetComposerTypes(TypeLoader typeLoader)
   at Umbraco.Core.Runtime.CoreRuntime.ResolveComposerTypes(TypeLoader typeLoader)
   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer)]
   Umbraco.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException) +226
   Umbraco.Web.Composing.ModuleInjector`1.Init(HttpApplication context) +192
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +523
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +176
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +220
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +303

**Comment by skttl** [comment]
Closing because of missing details.

**Comment by thenexus00** [comment]
* nstalling through the package manager in Umbraco.
* Umbraco version 8.5.3

What information do you need?

**Comment by skttl** [comment]
Thanks, DTGE 1.2 requires Umbraco 8.6 as a minimum. Go with 1.1 in stead, or upgrade your Umbraco install.
