### ISSUE TITLE
Null Pointer Exception on save when no grid layout selected

### ISSUE THREAD

**Issue by theotherpotter** [skttl/umbraco-doc-type-grid-editor#211]
I'm running Umbraco 8.6.2 on Umbraco Cloud.  

If I create a page which has a grid as a property but no grid layout is selected I get the following error on save.  We can work around it by putting a blank headline in a row but it's not an ideal user experience. 

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Our.Umbraco.DocTypeGridEditor
  StackTrace:
   at Our.Umbraco.DocTypeGridEditor.ValueProcessing.DocTypeGridEditorDataValueReference.DeserializeGridValue(String rawJson, IEnumerable`1& dtgeValues)
   at Our.Umbraco.DocTypeGridEditor.ValueProcessing.DocTypeGridEditorDataValueReference.GetReferences(Object value)
   at Umbraco.Core.PropertyEditors.DataValueReferenceFactoryCollection.GetAllReferences(PropertyCollection properties, PropertyEditorCollection propertyEditors) in D:\a\1\s\src\Umbraco.Core\PropertyEditors\DataValueReferenceFactoryCollection.cs:line 48
   at Umbraco.Core.Persistence.Repositories.Implement.ContentRepositoryBase`3.PersistRelations(TEntity entity) in D:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\ContentRepositoryBase.cs:line 829
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.PersistUpdatedItem(IContent entity) in D:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\DocumentRepository.cs:line 708
   at Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated) in D:\a\1\s\src\Umbraco.Core\Cache\DefaultRepositoryCachePolicy.cs:line 128
   at Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase`2.Save(TEntity entity) in D:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\RepositoryBaseOfTIdTEntity.cs:line 140
   at Umbraco.Core.Services.Implement.ContentService.<>c__DisplayClass57_0.<CommitDocumentChangesInternal>g__SaveDocument|2(IContent c) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1135
   at Umbraco.Core.Services.Implement.ContentService.CommitDocumentChangesInternal(IScope scope, IContent content, ContentSavingEventArgs saveEventArgs, IReadOnlyCollection`1 allLangs, Int32 userId, Boolean raiseEvents, Boolean branchOne, Boolean branchRoot) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1227
   at Umbraco.Core.Services.Implement.ContentService.SaveAndPublish(IContent content, String culture, Int32 userId, Boolean raiseEvents) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 903
   at Umbraco.Web.Editors.ContentController.PublishInternal(ContentItemSave contentItem, String defaultCulture, String cultureForInvariantErrors, Boolean& wasCancelled, String[]& successfulCultures) in D:\a\1\s\src\Umbraco.Web\Editors\ContentController.cs:line 1278
   at Umbraco.Web.Editors.ContentController.PostSaveInternal(ContentItemSave contentItem, Func`2 saveMethod, Func`2 mapToDisplay) in D:\a\1\s\src\Umbraco.Web\Editors\ContentController.cs:line 728
   at Umbraco.Web.Editors.ContentController.PostSave(ContentItemSave contentItem) in D:\a\1\s\src\Umbraco.Web\Editors\ContentController.cs:line 599
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

  This exception was originally thrown at this call stack:
    Our.Umbraco.DocTypeGridEditor.ValueProcessing.DocTypeGridEditorDataValueReference.DeserializeGridValue(string, out System.Collections.Generic.IEnumerable<Our.Umbraco.DocTypeGridEditor.Models.DocTypeGridEditorValue>)
    Our.Umbraco.DocTypeGridEditor.ValueProcessing.DocTypeGridEditorDataValueReference.GetReferences(object)
    Umbraco.Core.PropertyEditors.DataValueReferenceFactoryCollection.GetAllReferences(Umbraco.Core.Models.PropertyCollection, Umbraco.Core.PropertyEditors.PropertyEditorCollection) in DataValueReferenceFactoryCollection.cs
    Umbraco.Core.Persistence.Repositories.Implement.ContentRepositoryBase<TId, TEntity, TRepository>.PersistRelations(TEntity) in ContentRepositoryBase.cs
    Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.PersistUpdatedItem(Umbraco.Core.Models.IContent) in DocumentRepository.cs
    Umbraco.Core.Cache.DefaultRepositoryCachePolicy<TEntity, TId>.Update(TEntity, System.Action<TEntity>) in DefaultRepositoryCachePolicy.cs
    Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase<TId, TEntity>.Save(TEntity) in RepositoryBaseOfTIdTEntity.cs
    Umbraco.Core.Services.Implement.ContentService.CommitDocumentChangesInternal.__SaveDocument|2(Umbraco.Core.Models.IContent) in ContentService.cs
    Umbraco.Core.Services.Implement.ContentService.CommitDocumentChangesInternal(Umbraco.Core.Scoping.IScope, Umbraco.Core.Models.IContent, Umbraco.Core.Events.ContentSavingEventArgs, System.Collections.Generic.IReadOnlyCollection<Umbraco.Core.Models.ILanguage>, int, bool, bool, bool) in ContentService.cs
    Umbraco.Core.Services.Implement.ContentService.SaveAndPublish(Umbraco.Core.Models.IContent, string, int, bool) in ContentService.cs
    ...
    [Call Stack Truncated]

**Comment by Emetico** [comment]
I can confirm this issue on a blank Umbraco 8.6.3 & Doc Type Grid Editor 1.2.3 install, where you create a grid layout with more then one layout to choose from.

Like this post on [our.umbraco.com](https://our.umbraco.com/packages/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback//103082-dtge-error-when-using-multiple-grid-layouts-in-same-grid)

**Comment by slombardo** [comment]
I also had this issue.  I tested this fix locally by compiling and replacing the Our.Umbraco.DocTypeGridEditor.dll in my main project with the one I fixed in my PR #213, and it worked!

This was a show stopper for me.  I was dead in my tracks.

**Comment by skttl** [comment]
Fixed in #213
