### ISSUE TITLE
Exception when a layout is not chosen

### ISSUE THREAD

**Issue by AaronSadlerUK** [skttl/umbraco-doc-type-grid-editor#219]
When saving a content item which has multiple layouts on a grid, and nothing is chosen, a null exception is thrown:

![image](https://user-images.githubusercontent.com/9937803/92725199-ac860e80-f363-11ea-96ac-337c15d081dc.png)

```Unhandled controller exception occurred for request '"/umbraco/backoffice/UmbracoApi/Content/PostSave"'
									
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Our.Umbraco.DocTypeGridEditor.ValueProcessing.DocTypeGridEditorDataValueReference.DeserializeGridValue(String rawJson, IEnumerable`1& dtgeValues)
   at Our.Umbraco.DocTypeGridEditor.ValueProcessing.DocTypeGridEditorDataValueReference.GetReferences(Object value)
   at Umbraco.Core.PropertyEditors.DataValueReferenceFactoryCollection.GetAllReferences(PropertyCollection properties, PropertyEditorCollection propertyEditors)
   at Umbraco.Core.Persistence.Repositories.Implement.ContentRepositoryBase`3.PersistRelations(TEntity entity)
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.PersistUpdatedItem(IContent entity)
   at Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)
   at Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase`2.Save(TEntity entity)
   at Umbraco.Core.Services.Implement.ContentService.Save(IContent content, Int32 userId, Boolean raiseEvents)
   at Umbraco.Web.Editors.ContentController.<>c__DisplayClass29_0.<PostSave>b__0(IContent content)
   at Umbraco.Web.Editors.ContentController.SaveAndNotify(ContentItemSave contentItem, Func`2 saveMethod, Int32 variantCount, Dictionary`2 notifications, SimpleNotificationModel globalNotifications, String invariantSavedLocalizationKey, String variantSavedLocalizationKey, String cultureForInvariantErrors, Boolean& wasCancelled)
   at Umbraco.Web.Editors.ContentController.PostSaveInternal(ContentItemSave contentItem, Func`2 saveMethod, Func`2 mapToDisplay)
   at Umbraco.Web.Editors.ContentController.PostSave(ContentItemSave contentItem)```

**Comment by skttl** [comment]
Fixed in 1.2.4 :)
