### ISSUE TITLE
Umbraco 9 RC - package.manifest keeps regenerating

### ISSUE THREAD

**Issue by javz3** [skttl/umbraco-doc-type-grid-editor#252]
Hi, 

I've been updating the default DTGE /App_Plugins/DocTypeGridEditor/package.manifest to allow individual editors to show when selecting from a grid:

`{
  "gridEditors": [
    {
      "name": "Doc Type",
      "alias": "docType",
      "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
      "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
      "icon": "icon-science",
      "config": {
        "allowedDocTypes": [],
        "nameTemplate": "",
        "enablePreview": true,
        "viewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/",
        "previewViewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/",
        "previewCssFilePath": "",
        "previewJsFilePath": ""
      }
    },
    {
      "name": "Embed Video",
      "alias": "embedVideo",
      "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
      "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
      "icon": "icon-science",
      "config": {
        "allowedDocTypes": [ "embedVideo" ],
        "nameTemplate": "",
        "enablePreview": true,
        "viewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/",
        "previewViewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/",
        "previewCssFilePath": "",
        "previewJsFilePath": ""
      }
    }
  ],
  "javascript": [
    "~/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.resources.js",
    "~/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.services.js",
    "~/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.controllers.js",
    "~/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.directives.js"
  ],
  "css": [
    "~/App_Plugins/DocTypeGridEditor/Css/doctypegrideditor.css"
  ]
}
`

However with each build, it appears to reinstall the DTGE, overriding any changes I make.

Any ideas why?

EDIT:

I also tried to create a separate package.manifest file mimicking the one from DTGE - this time it appears, however when selected it throws the following error:

`Received an error from the server
An error occurred
Value cannot be null. (Parameter 'pattern')

Exception Details
System.ArgumentNullException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Value cannot be null. (Parameter 'pattern')
Stacktrace
at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.RegexCache.GetOrAdd(String pattern)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
   at Our.Umbraco.DocTypeGridEditor.Controllers.DocTypeGridEditorApiController.<>c__DisplayClass13_1.<GetContentTypes>b__5(String y)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Our.Umbraco.DocTypeGridEditor.Controllers.DocTypeGridEditorApiController.<>c__DisplayClass13_0.<GetContentTypes>b__1(IContentType x)
   at System.Linq.Enumerable.WhereListIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at Our.Umbraco.DocTypeGridEditor.Controllers.DocTypeGridEditorApiController.GetContentTypes(String[] allowedContentTypes)
   at lambda_method733(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

Since it mentioned Regex, I had then updated the document type that I used as part of the DTGE, which had a textarea and a textstring, and added an email validation to both (just for testing) and the same error message still persisted.

Thanks

**Comment by skttl** [comment]
I guess that is how net core works, on build the package files gets copied into wwwroot. You should add your own package.manifests for your own editors.

**Comment by javz3** [comment]
Hi @skttl 

I did create my own package.manifests files and you can see the error message pasted above. Here it is again:

I also tried to create a separate package.manifest file mimicking the one from DTGE - this time it appears, however when selected it throws the following error:

`Received an error from the server
An error occurred
Value cannot be null. (Parameter 'pattern')

Exception Details
System.ArgumentNullException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Value cannot be null. (Parameter 'pattern')
Stacktrace
at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
at System.Text.RegularExpressions.RegexCache.GetOrAdd(String pattern)
at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
at Our.Umbraco.DocTypeGridEditor.Controllers.DocTypeGridEditorApiController.<>c__DisplayClass13_1.b__5(String y)
at System.Linq.Enumerable.Any[TSource](IEnumerable1 source, Func2 predicate)
at Our.Umbraco.DocTypeGridEditor.Controllers.DocTypeGridEditorApiController.<>c__DisplayClass13_0.b__1(IContentType x)
at System.Linq.Enumerable.WhereListIterator1.ToArray() at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.OrderedEnumerable1.ToList()
at Our.Umbraco.DocTypeGridEditor.Controllers.DocTypeGridEditorApiController.GetContentTypes(String[] allowedContentTypes)
at lambda_method733(Closure , Object , Object[] )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

Since it mentioned Regex, I had then updated the document type that I used as part of the DTGE, which had a textarea and a textstring, and added an email validation to both (just for testing) and the same error message still persisted.

**Comment by skttl** [comment]
That has already been reported in #251, its a "bug/feature" in core. Not sure how to fix yet.

**Comment by javz3** [comment]
I see, thanks for the quick responses @skttl

**Comment by skttl** [comment]
You are welcome, thanks for testing the beta 🙂

**Comment by alandraper** [comment]
I don't understand this. Are we supposed to change the default package.manifest, or create a new one? When I change the default it gets overwritten whenever I build. I've never had multiple package.manifest files... can I just create a new .manifest file with a different name? I tried that and I still only get the (docType) and (picture) entries.

**Comment by alandraper** [comment]
OK, I think I get it. I made a new folder App_Plugins/MyVerySpecialDocTypeGridEditors and added a package.manifest in there. 

Seems less than ideal -- I still have the generic "Doc Type" and "Picture" available -- but it works. 

![Screenshot 2021-09-19 100820](https://user-images.githubusercontent.com/13674761/133936430-ed8e6d0f-0f61-433a-84a9-11e04437da1c.png)
